filters:
  issue:
#    asset_id: null
#    asset_name: null
#    asset_type: server
#    cp_rule_id: null
    critical: true
#    csp_account_id: null
#    csp_account_name: null
#    csp_account_type: null
#    csp_image_id: ami-01bbe152bf19d0289
#    csp_region: null
#    csp_resource_id: "i-0d318864f4a276ea4"
#    csp_resource_uri: null
#    csp_service_type: null
#    csp_tags:
#      environment: "production"
#    cve_id:
#      - null
#      - null
#    first_seen_at: wrong
#    group_name: customer-success
#    image_sha: null
#    name: null
    source: server_secure
    type: ["fim", "csm"]
#    last_seen_at: wrong
#    max_cvss_gte: 7.0
#    os_type: linux
#    policy_name: CIS AWS Foundations Benchmark Customized v1.2 2019-07-11
#    registry_id: null
#    registry_name: null
#    repository_id: null
#    repository_name: null
#    resolved_at: wrong
#  asset:
#    created_at: "2019-09-27T19:39:32.738Z"
#    hostname: "ip-172-31-16-78"
#    server_label: null
#    reported_fqdn: "ip-172-31-16-78.us-west-2.compute.internal"
#    primary_ip_address: "172.31.16.78"
#    connecting_ip_address: "35.166.72.122"
#    state: "active"
#    daemon_version: "4.2.6"
#    read_only: false
#    platform: "ubuntu"
#    platform_version: "18.04"
#    os_version: "4.15.0-1044-aws"
#    kernel_name: "Linux"
#    kernel_machine: "x86_64"
#    self_verification_failed: false
#    connecting_ip_fqdn: "ec2-35-166-72-122.us-west-2.compute.amazonaws.com"
#    last_state_change: "2019-09-27T19:39:32.739Z"
#    docker_inspection: "Disabled"
#    group_id: "91e35454024511e9a8444b54e5ae6c14"
#    group_name: "CloudPassage Demo"
#    firewall_policy: null


